/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Id = IDL.Nat;
export const T__2 = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'authorId' : IDL.Vec(IDL.Nat8),
  'authorName' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'blobId' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Reaction = IDL.Record({
  'userId' : IDL.Vec(IDL.Nat8),
  'emoji' : IDL.Text,
});
export const T = IDL.Record({
  'id' : IDL.Nat,
  'authorId' : IDL.Vec(IDL.Nat8),
  'text' : IDL.Text,
  'authorName' : IDL.Text,
  'timestamp' : IDL.Int,
  'reactions' : IDL.Vec(Reaction),
});
export const Emotion = IDL.Variant({
  'sad' : IDL.Null,
  'tired' : IDL.Null,
  'happy' : IDL.Null,
  'calm' : IDL.Null,
  'stressed' : IDL.Null,
  'excited' : IDL.Null,
});
export const T__1 = IDL.Record({
  'emotion' : Emotion,
  'userId' : IDL.Vec(IDL.Nat8),
  'date' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addReaction' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMemory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [T__2],
      [],
    ),
  'deleteMemory' : IDL.Func([IDL.Nat], [], []),
  'getBlobLink' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyPrompt' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'getMemories' : IDL.Func([], [IDL.Vec(T__2)], ['query']),
  'getMessages' : IDL.Func([], [IDL.Vec(T)], ['query']),
  'getStartDate' : IDL.Func([], [IDL.Text], ['query']),
  'getTodayCheckIns' : IDL.Func([IDL.Text], [IDL.Vec(T__1)], ['query']),
  'getUserCheckIn' : IDL.Func([IDL.Text], [IDL.Opt(T__1)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerWithInviteCode' : IDL.Func([IDL.Text, UserProfile], [], []),
  'removeReaction' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [T], []),
  'submitCheckIn' : IDL.Func([IDL.Text, Emotion], [], []),
  'updateInviteCode' : IDL.Func([IDL.Text], [], []),
  'updateStartDate' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Id = IDL.Nat;
  const T__2 = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'authorId' : IDL.Vec(IDL.Nat8),
    'authorName' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'blobId' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Reaction = IDL.Record({
    'userId' : IDL.Vec(IDL.Nat8),
    'emoji' : IDL.Text,
  });
  const T = IDL.Record({
    'id' : IDL.Nat,
    'authorId' : IDL.Vec(IDL.Nat8),
    'text' : IDL.Text,
    'authorName' : IDL.Text,
    'timestamp' : IDL.Int,
    'reactions' : IDL.Vec(Reaction),
  });
  const Emotion = IDL.Variant({
    'sad' : IDL.Null,
    'tired' : IDL.Null,
    'happy' : IDL.Null,
    'calm' : IDL.Null,
    'stressed' : IDL.Null,
    'excited' : IDL.Null,
  });
  const T__1 = IDL.Record({
    'emotion' : Emotion,
    'userId' : IDL.Vec(IDL.Nat8),
    'date' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addReaction' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMemory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [T__2],
        [],
      ),
    'deleteMemory' : IDL.Func([IDL.Nat], [], []),
    'getBlobLink' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyPrompt' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'getMemories' : IDL.Func([], [IDL.Vec(T__2)], ['query']),
    'getMessages' : IDL.Func([], [IDL.Vec(T)], ['query']),
    'getStartDate' : IDL.Func([], [IDL.Text], ['query']),
    'getTodayCheckIns' : IDL.Func([IDL.Text], [IDL.Vec(T__1)], ['query']),
    'getUserCheckIn' : IDL.Func([IDL.Text], [IDL.Opt(T__1)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerWithInviteCode' : IDL.Func([IDL.Text, UserProfile], [], []),
    'removeReaction' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [T], []),
    'submitCheckIn' : IDL.Func([IDL.Text, Emotion], [], []),
    'updateInviteCode' : IDL.Func([IDL.Text], [], []),
    'updateStartDate' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };