/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Emotion = { 'sad' : null } |
  { 'tired' : null } |
  { 'happy' : null } |
  { 'calm' : null } |
  { 'stressed' : null } |
  { 'excited' : null };
export type Id = bigint;
export interface Reaction { 'userId' : Uint8Array, 'emoji' : string }
export interface T {
  'id' : bigint,
  'authorId' : Uint8Array,
  'text' : string,
  'authorName' : string,
  'timestamp' : bigint,
  'reactions' : Array<Reaction>,
}
export interface T__1 {
  'emotion' : Emotion,
  'userId' : Uint8Array,
  'date' : string,
}
export interface T__2 {
  'id' : Id,
  'title' : string,
  'authorId' : Uint8Array,
  'authorName' : string,
  'description' : [] | [string],
  'timestamp' : bigint,
  'blobId' : [] | [string],
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReaction' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMemory' : ActorMethod<
    [string, string, [] | [string], [] | [string]],
    T__2
  >,
  'deleteMemory' : ActorMethod<[bigint], undefined>,
  'getBlobLink' : ActorMethod<[string], [] | [string]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyPrompt' : ActorMethod<[bigint], string>,
  'getMemories' : ActorMethod<[], Array<T__2>>,
  'getMessages' : ActorMethod<[], Array<T>>,
  'getStartDate' : ActorMethod<[], string>,
  'getTodayCheckIns' : ActorMethod<[string], Array<T__1>>,
  'getUserCheckIn' : ActorMethod<[string], [] | [T__1]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerWithInviteCode' : ActorMethod<[string, UserProfile], undefined>,
  'removeReaction' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[string, string], T>,
  'submitCheckIn' : ActorMethod<[string, Emotion], undefined>,
  'updateInviteCode' : ActorMethod<[string], undefined>,
  'updateStartDate' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];