/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Reaction {
    sessionId: string;
    emoji: string;
}
export interface T__2 {
    id: Id;
    title: string;
    authorId: string;
    authorName: string;
    description?: string;
    timestamp: bigint;
    blobId?: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface T__1 {
    emotion: Emotion;
    sessionId: string;
    date: string;
}
export interface T {
    id: bigint;
    authorId: string;
    text: string;
    authorName: string;
    timestamp: bigint;
    reactions: Array<Reaction>;
}
export type Id = bigint;
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Emotion {
    sad = "sad",
    tired = "tired",
    happy = "happy",
    calm = "calm",
    stressed = "stressed",
    excited = "excited"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    registerUser(sessionId: string, name: string, passkey: string): Promise<void>;
    getProfile(sessionId: string): Promise<UserProfile | null>;
    saveProfile(sessionId: string, profile: UserProfile): Promise<void>;
    getStartDate(): Promise<string>;
    updateStartDate(sessionId: string, date: string): Promise<void>;
    submitCheckIn(sessionId: string, date: string, emotion: Emotion): Promise<void>;
    getTodayCheckIns(date: string): Promise<Array<T__1>>;
    getUserCheckIn(sessionId: string, date: string): Promise<T__1 | null>;
    getDailyPrompt(dayOfYear: bigint): Promise<string>;
    sendMessage(sessionId: string, authorName: string, text: string): Promise<T>;
    addReaction(sessionId: string, messageId: bigint, emoji: string): Promise<void>;
    removeReaction(sessionId: string, messageId: bigint, emoji: string): Promise<void>;
    getMessages(): Promise<Array<T>>;
    createMemory(sessionId: string, authorName: string, title: string, description: string | null, blobId: string | null): Promise<T__2>;
    deleteMemory(sessionId: string, memoryId: bigint): Promise<void>;
    getMemories(): Promise<Array<T__2>>;
}
import type { Emotion as _Emotion, Id as _Id, T__1 as _T__1, T__2 as _T__2, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}

    private async _call<T>(fn: () => Promise<T>): Promise<T> {
        if (this.processError) {
            try {
                return await fn();
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        }
        return await fn();
    }

    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        return this._call(() => this.actor._caffeineStorageBlobIsLive(arg0));
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        return this._call(() => this.actor._caffeineStorageBlobsToDelete());
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        return this._call(() => this.actor._caffeineStorageConfirmBlobDeletion(arg0));
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        return this._call(() => this.actor._caffeineStorageCreateCertificate(arg0));
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        return this._call(async () => {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        });
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        return this._call(() => this.actor._caffeineStorageUpdateGatewayPrincipals());
    }

    // New sessionId-based auth methods
    async registerUser(sessionId: string, name: string, passkey: string): Promise<void> {
        return this._call(() => (this.actor as any).registerUser(sessionId, name, passkey));
    }
    async getProfile(sessionId: string): Promise<UserProfile | null> {
        return this._call(async () => {
            const result = await (this.actor as any).getProfile(sessionId);
            return result.length === 0 ? null : result[0];
        });
    }
    async saveProfile(sessionId: string, profile: UserProfile): Promise<void> {
        return this._call(() => (this.actor as any).saveProfile(sessionId, profile));
    }
    async getStartDate(): Promise<string> {
        return this._call(() => (this.actor as any).getStartDate());
    }
    async updateStartDate(sessionId: string, date: string): Promise<void> {
        return this._call(() => (this.actor as any).updateStartDate(sessionId, date));
    }
    async submitCheckIn(sessionId: string, date: string, emotion: Emotion): Promise<void> {
        return this._call(() => (this.actor as any).submitCheckIn(sessionId, date, to_candid_Emotion_n24(this._uploadFile, this._downloadFile, emotion)));
    }
    async getTodayCheckIns(date: string): Promise<Array<T__1>> {
        return this._call(async () => {
            const result = await (this.actor as any).getTodayCheckIns(date);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        });
    }
    async getUserCheckIn(sessionId: string, date: string): Promise<T__1 | null> {
        return this._call(async () => {
            const result = await (this.actor as any).getUserCheckIn(sessionId, date);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        });
    }
    async getDailyPrompt(dayOfYear: bigint): Promise<string> {
        return this._call(() => (this.actor as any).getDailyPrompt(dayOfYear));
    }
    async sendMessage(sessionId: string, authorName: string, text: string): Promise<T> {
        return this._call(() => (this.actor as any).sendMessage(sessionId, authorName, text));
    }
    async addReaction(sessionId: string, messageId: bigint, emoji: string): Promise<void> {
        return this._call(() => (this.actor as any).addReaction(sessionId, messageId, emoji));
    }
    async removeReaction(sessionId: string, messageId: bigint, emoji: string): Promise<void> {
        return this._call(() => (this.actor as any).removeReaction(sessionId, messageId, emoji));
    }
    async getMessages(): Promise<Array<T>> {
        return this._call(() => (this.actor as any).getMessages());
    }
    async createMemory(sessionId: string, authorName: string, title: string, description: string | null, blobId: string | null): Promise<T__2> {
        return this._call(async () => {
            const result = await (this.actor as any).createMemory(
                sessionId, authorName, title,
                to_candid_opt_n10(this._uploadFile, this._downloadFile, description),
                to_candid_opt_n10(this._uploadFile, this._downloadFile, blobId)
            );
            return from_candid_T__2_n11(this._uploadFile, this._downloadFile, result);
        });
    }
    async deleteMemory(sessionId: string, memoryId: bigint): Promise<void> {
        return this._call(() => (this.actor as any).deleteMemory(sessionId, memoryId));
    }
    async getMemories(): Promise<Array<T__2>> {
        return this._call(async () => {
            const result = await (this.actor as any).getMemories();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        });
    }
}

function from_candid_Emotion_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Emotion): Emotion {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_T__1_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T__1): T__1 {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_T__2_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T__2): T__2 {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_T__1]): T__1 | null {
    return value.length === 0 ? null : from_candid_T__1_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    title: string;
    authorId: Uint8Array;
    authorName: string;
    description: [] | [string];
    timestamp: bigint;
    blobId: [] | [string];
}): {
    id: Id;
    title: string;
    authorId: Uint8Array;
    authorName: string;
    description?: string;
    timestamp: bigint;
    blobId?: string;
} {
    return {
        id: value.id,
        title: value.title,
        authorId: value.authorId,
        authorName: value.authorName,
        description: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.description)),
        timestamp: value.timestamp,
        blobId: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.blobId))
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    emotion: _Emotion;
    userId: Uint8Array;
    date: string;
}): {
    emotion: Emotion;
    userId: Uint8Array;
    date: string;
} {
    return {
        emotion: from_candid_Emotion_n21(_uploadFile, _downloadFile, value.emotion),
        userId: value.userId,
        date: value.date
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sad: null;
} | {
    tired: null;
} | {
    happy: null;
} | {
    calm: null;
} | {
    stressed: null;
} | {
    excited: null;
}): Emotion {
    return "sad" in value ? Emotion.sad : "tired" in value ? Emotion.tired : "happy" in value ? Emotion.happy : "calm" in value ? Emotion.calm : "stressed" in value ? Emotion.stressed : "excited" in value ? Emotion.excited : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_T__2>): Array<T__2> {
    return value.map((x)=>from_candid_T__2_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_T__1>): Array<T__1> {
    return value.map((x)=>from_candid_T__1_n19(_uploadFile, _downloadFile, x));
}
function to_candid_Emotion_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Emotion): _Emotion {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Emotion): {
    sad: null;
} | {
    tired: null;
} | {
    happy: null;
} | {
    calm: null;
} | {
    stressed: null;
} | {
    excited: null;
} {
    return value == Emotion.sad ? {
        sad: null
    } : value == Emotion.tired ? {
        tired: null
    } : value == Emotion.happy ? {
        happy: null
    } : value == Emotion.calm ? {
        calm: null
    } : value == Emotion.stressed ? {
        stressed: null
    } : value == Emotion.excited ? {
        excited: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}

export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
